spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: on
server:
  port: 2222

logging:
  level:
    tacos: DEBUG

taco:
  orders:
  pageSize: 10


---
spring:
  config:
    activate:
      on-profile: "prod"

  datasource:
  url: jdbc:mysql:/ /localhost/tacocloud
  username: tacouser
  password: tacopassword

logging:
  level:
    tacos: WARN